<?xml version="1.0" encoding="utf-8"?><Database Name="Schedule" Class="ScheduleModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\ninor\source\repos\ScheduleSite\ScheduleSite\App_Data\Schedule.mdf;Integrated Security=True" SettingsObjectName="ScheduleItem.Properties.Settings" SettingsPropertyName="ScheduleConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ScheduleItems" Member="ScheduleItems">
    <Type Name="ScheduleItem">
      <Column Name="Day" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Lesson" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Classroom" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Teacher" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>